# action名称
name: Push Release

# 当代码合并到master分支的时候，执行下列脚本
on:
  push:
    branches: [ master ]

# 任务
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: 检查master分支
        uses: actions/checkout@v1

      - name: 设置Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 安装依赖
        run: npm i

      - name: 构建packages
        run: npm run lib

      - name: 发布NPM包
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          # NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: 
          # npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish
      - name: publish 成功通知
        run: echo npm 推送成功，请访问 https://jackysoft.github.io/rocket-render-doc

      # - name: 读取当前版本号
      #   id: version
      #   uses: ashley-taylor/read-json-property-action@v1.0
      #   with:
      #     path: ./package.json
      #     property: version

      # - name: 创建GitHub Release
      #   id: create_release
      #   uses: actions/create-release@latest
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{steps.version.outputs.value}}
      #     release_name: v${{steps.version.outputs.value}}
      #     draft: false
      #     prerelease: false
